### ISSUE TITLE
As a dev, I want to fix the swagger on the deployment

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/fertiscan-backend#136]
## Description  

**Bug Summary:** 
On the deployed `fertiscan-backend`, the swagger is not functional

**Steps to Reproduce:**  
https://fertiscan.inspection.alpha.canada.ca/api/apidocs

**Expected Behavior:**  
Should display the swagger doc.

**Actual Behavior:**  
Doesn't load the swagger.

**Suggested Fix:**
Check the root path where swagger is mounted.

**Comment by Youllou** [comment]
https://stackoverflow.com/questions/61479914/swagger-change-base-url-in-python-using-flasgger-library
might be a solution
