### ISSUE TITLE
As a dev, I want to deploy the application using a WSGI server

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/fertiscan-backend#137]
## Description  

**Context**
Currently, our Dockerfile uses `python app.py` to deploy the application. This method is fine for development but not ideal for production environments, where a WSGI server is recommended for better performance and handling of concurrent requests.

**Problem Statement**
Running the application directly with `python app.py` is not suitable for production as it lacks the robustness and efficiency provided by a WSGI server. This could lead to performance issues and difficulties in handling multiple requests in a real-world scenario.

**Acceptance Criteria**  
- Replace `CMD ["python", "app.py"]` in the Dockerfile with a command that uses a WSGI server (e.g., `gunicorn` or `uWSGI`).
- Ensure that the WSGI server is correctly configured to serve the application in production.
- Update the Dockerfile to reflect this change and ensure it builds successfully.
- Test the deployment to verify that the application works as expected under the new setup.

**Additional Information** (Optional)  
For reference, consult the [Flask deployment documentation](https://flask.palletsprojects.com/en/3.0.x/deploying/) on using a WSGI server.

**Comment by SonOfLope** [comment]
@k-allagbe fyi this was done in previous iteration where i integrated auto-instrumentation and was necessary to make it work. Can we mark this as done ?

https://github.com/ai-cfia/fertiscan-backend/blob/2fa132bb10e5958ec177005b62622d332d0c83a1/Dockerfile#L42

**Comment by k-allagbe** [comment]
Done in #210.
