### ISSUE TITLE
As a developer, I want to resolve the authentication issue with the inspections swagger routes

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/fertiscan-backend#144]
## Description  

**Bug Summary:**  
When attempting to use the inspections swagger routes, an authentication problem arises. The response returns an error stating that the user could not be retrieved.

**Steps to Reproduce:**  
1. Use the inspections swagger routes.
2. Observe the error response.

**Expected Behavior:**  
The route should be usable.

**Actual Behavior:**  
![Image](https://github.com/user-attachments/assets/1300fbcb-8af7-4695-ace8-99bded9adb9b)

Backend error:  
```bash
2024-09-09 16:13:35,413 - app - INFO - Fetching user ID for username: 
2024-09-09 16:13:35,436 - app - ERROR - Error occurred: Error: user  could not be retrieved
```

**Comment by snakedye** [comment]
@k-allagbe The user must be logged in first.
![image](https://github.com/user-attachments/assets/404974fe-e5b9-4e71-a497-6d11d53d965c)
![image](https://github.com/user-attachments/assets/2e2dc887-5aa3-41b1-9b43-1c5d7de55240)

**Comment by Francois-Werbrouck** [comment]
Hi, alot of changes happened recently. I advise using the branch `149-guaranteed-analysis-title-in-fertiscan` from the datastore

https://github.com/ai-cfia/ailab-datastore/issues/149

**Comment by snakedye** [comment]
@Francois-Werbrouck  The only error.
```
  File "/workspaces/fertiscan-backend/tests/test_app.py", line 197, in test_get_inspection_by_id
    self.assertEqual(response.status_code, 201, response.get_json())
AssertionError: 500 != 201 : {'error': "Missing keys:['guaranteed_analysis_is_minimal']"}
```

**Comment by k-allagbe** [comment]
Tested with the authorize button, working as expected. Closing this. Please reopen if any other related issue is noted.
