### ISSUE TITLE
Ollama support

### ISSUE THREAD

**Issue by snakedye** [ai-cfia/fertiscan-backend#36]
Add a class that serves as a client for our Ollama instance.

* https://github.com/ollama/ollama/blob/main/docs/api.md
* https://github.com/ollama/ollama-python

 Tasks:

 * [ ] `ollama.py`
 * [ ] test it in `test_language_model.py`
 
 Acceptance Criteria:

* All the tests should pass.
* Test with real ollama endpoint.

**Comment by SonOfLope** [comment]
From nginx-ingress logs : 
2024/06/03 14:54:59 [error] 31#31: *183113 access forbidden by rule, client: 172.172.208.244, server: ollama.inspection.alpha.canada.ca, request: "POST /api/chat HTTP/1.1", host: "ollama.inspection.alpha.canada.ca"
We'll have to see how we want to enable request coming from codespaces

**Comment by Endlessflow** [comment]
Support for Ollama and local models is no longer being considered. It seems unnecessary to keep this issue open any longer.
