### ISSUE TITLE
Correct the system prompt.

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [ai-cfia/fertiscan-backend#50]
Improve the system prompt to yield better result.

 Tasks:

 * [ ] Rewrite the prompt at ``./prompt.txt`

 Acceptance Criteria:

* The prompt should be in english.
* All the fields in the database should be present.
* The output should be a complete JSON

**Comment by Endlessflow** [comment]
This appears to be a duplicate of issue #66, which has already been closed. I will proceed to close this one as well.
