### ISSUE TITLE
As a developer, I want our unit tests to correctly retrieve environment variables from both the local .env file and OS environment variables.

### ISSUE THREAD

**Issue by Endlessflow** [ai-cfia/fertiscan-backend#64]
## Context

Currently, our testing workflows consistently fail when attempting to run unit tests. The primary hypothesis is that our tests are retrieving environment variables from a local `.env` file instead of using the OS environment variables. This discrepancy leads to failures in our GitHub Actions because the required keys are missing from the `.env` file but are present as GitHub secrets.

This issue impacts the reliability of our continuous integration pipeline, causing delays and confusion among developers when tests pass locally but fail in CI/CD environments.

## Acceptance Criteria
- Modify the unit tests to check for environment variables from the local `.env` file first, and if not found, then fall back to the OS environment variables.
- Ensure compatibility with both local development setups and CI/CD pipelines in GitHub Actions.
- Validate the solution by confirming that unit tests pass consistently both locally and within the GitHub Actions environment.

**Comment by SonOfLope** [comment]
> We already use the [OS environment variables](https://github.com/ai-cfia/fertiscan-backend/blob/41af40ea55c4b841d5fbfed2a6cbeb643be9f7d0/app.py#L17). What `dotenv` does is load the variables in `.env` as OS environment variables.
> 
> The testing workflow also doesn't use Github Secrets AFAIK. It's still a bit foggy but what I recall from what @SonOfLope told me is that what is currently used to handle secrets isn't really fit with the way workflows are run so they're migrating to something Azure related so everything can be in the same place.

It is using github secrets as of yesterday.

**Comment by SonOfLope** [comment]
> We already use the [OS environment variables](https://github.com/ai-cfia/fertiscan-backend/blob/41af40ea55c4b841d5fbfed2a6cbeb643be9f7d0/app.py#L17). What `dotenv` does is load the variables in `.env` as OS environment variables.
> 
> The testing workflow also doesn't use Github Secrets AFAIK. It's still a bit foggy but what I recall from what @SonOfLope told me is that what is currently used to handle secrets isn't really fit with the way workflows are run so they're migrating to something Azure related so everything can be in the same place.

The problem is you are 'only' loading from .env. In production, these variables will be available as environment variables and not in a .env file. As such, you will need to fetch them directly from the OS environment variables.

**Comment by snakedye** [comment]
> It is using github secrets as of yesterday.

Thanks, so I suppose all that's left is to put the variables there?

**Comment by SonOfLope** [comment]
No, y

> > It is using github secrets as of yesterday.
> 
> Thanks, so I suppose all that's left is to put the variables there?

You also need to fetch the variables in the code. Example: Nachet doing both loading from .env and directly fetching the variables : https://github.com/ai-cfia/nachet-backend/blob/main/app.py

**Comment by snakedye** [comment]
> The problem is you are 'only' loading from .env. In production, these variables will be available as environment variables and not in a .env file. As such, you will need to fetch them directly from the OS environment variables.

[load_env](https://github.com/ai-cfia/fertiscan-backend/blob/41af40ea55c4b841d5fbfed2a6cbeb643be9f7d0/app.py#L11) doesn't clear all the other environment variables and then load the ones in `.env`. It only loads the variables in `.env` so if the file is empty or a variable isn't present there, it will no effect on the other variables. I'm also not loading from `.env`, I'm loading from the [OS](https://github.com/ai-cfia/fertiscan-backend/blob/41af40ea55c4b841d5fbfed2a6cbeb643be9f7d0/app.py#L30).

I just made a test locally and it can pick up on env vars passed through the OS.

**Comment by SonOfLope** [comment]
it seems AZURE_OPENAI_KEY is missing.... @Endlessflow 

@snakedye can you add the variable to the repository secrets with right value. It should then fix the pipeline. Also looking at the code, you guys are already doing both loading from dotenv and from environment.

**Comment by snakedye** [comment]
@SonOfLope Done
![image](https://github.com/ai-cfia/fertiscan-backend/assets/49378990/8931705c-d7b8-4c80-b349-824f18a55621)

**Comment by SonOfLope** [comment]
@Endlessflow seems like theres more env variables than what you stated : 
![image](https://github.com/ai-cfia/fertiscan-backend/assets/73133692/97ea5b3e-6150-44d1-99f4-6ad7260cbe7a)

@snakedye could you please add secrets for all existing env variables haha

**Comment by snakedye** [comment]
I added all the others.
![image](https://github.com/ai-cfia/fertiscan-backend/assets/49378990/eff603fa-d8bf-4c8b-b3eb-e66727797248)

**Comment by SonOfLope** [comment]
![image](https://github.com/ai-cfia/fertiscan-backend/assets/73133692/4b483918-8762-4f17-92db-0b9524894833)
Congrats everyone. This issue can be closed.

**Comment by snakedye** [comment]
GG.
