### ISSUE TITLE
As a developer, I want validation for environment variables so that the backend does not start with missing or invalid configurations.

### ISSUE THREAD

**Issue by Endlessflow** [ai-cfia/fertiscan-backend#93]
### Context
The application relies on several environment variables for configuration, but it currently does not validate these variables at startup. This can lead to runtime errors and misconfigurations that are hard to debug.

### Problem to Solve
Implementing validation for environment variables at application startup will ensure that the application only runs with valid and complete configurations.

### Completion Criteria
- [x] Add a function to validate all required environment variables at startup.
- [x] Ensure the application exits with a clear error message if any required variable is missing or invalid.
- [x] Document the required environment variables and their valid values in the `README.md`.
- [x] Add unit tests to ensure the validation function works correctly.

**Comment by snakedye** [comment]
I checked the backend and there really is only one variable that we need to check and that's `UPLOAD_PATH` which can be set to 'uploads' by default. The rest are on the pipeline repo but the only thing not covered was the deployment and I fixed it in the [last commit](https://github.com/ai-cfia/fertiscan-pipeline/commit/58835c4d85815a38276df1a24f996bbf46476fa5#diff-09e937381379876d2856aab4ca3f89317db7fe97854fdcdb23de8878c2d2c25fR64).

**Comment by snakedye** [comment]
This is now done in the main for
* FERTISCAN_DB_URL
* FERTISCAN_SCHEMA
* FERTISCAN_STORAGE_URL

**Comment by snakedye** [comment]
@Endlessflow Your opinion?

**Comment by Endlessflow** [comment]
Yeah it looks good - we can indeed close this, thanks.
